SELECT

  P.CODPROD,
  P.DESCRICAO,
  I.DATA,
  I.NUMPED,
  I.CODCLI,
  I.QT,
  M.NUMCAR,
  M.NUMNOTA AS "Nota Movimentacao",
  N.NUMNOTA AS "NR Nota Fiscal",
  M.CODFILIAL,
  M.STATUS,
  N.CHAVENFE,
  N.SITUACAONFE

FROM

  PCPRODUT P,
  PCPEDI I,
  PCMOV M,
  PCNFSAID N
  
 wHERE

  P.CODPROD = M.CODPROD AND
  I.CODCLI  = M.CODCLI  AND
  I.NUMPED  = M.NUMPED  AND 
  I.CODCLI  <> '1'      AND -- FIXO
  P.CODPROD = '90410'   AND -- PARÂMETRO
  M.NUMNOTA = '4485459' AND -- PARÂMETRO
  M.DTMOV   >= '22/NOV/2022' 
  
  
